project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "First Challenge"
            file: Chapter_1_Challenge.Rmd
          - text: "Second Challenge"
            file: Chapter_2_Challenge.Rmd
          - text: "Third Challenge"
            file: Chapter_3_Challenge.Rmd
          - text: "Fourth Challenge"
            file: Chapter_4_Challenge.Rmd
          - text: "Fifth Challenge"
            file: Chapter_5_Challenge.Rmd
          - text: "Sixth Challenge"
            file: Chapter_6_Challenge.Rmd
      - text: "Class notes"
        file: content/02_notes/05_class_notes.qmd
      - text: "Links"
        file: content/03_other/06_links.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto